name: Notify when website changes

on:
  schedule:
    - cron:  '*/30 5-21 * * *' # every 30min

jobs:
  notify_thalwil_websites:
    uses: metaodi/website-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: website.csv
