name: Notify when website changes

on:
  schedule:
    - cron:  '*/15 * * * *' # every 15min
  workflow_dispatch:

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get install sqlite3

      - id: set-matrix
        run: |
          matrix=$(./matrix.sh)
          echo $matrix
          #echo "::set-output name=matrix::$matrix"
          echo "::set-output name=matrix::{\"include\": [{\"label\": \"Thalwil informiert\", \"url\": \"https://www.thalwil.ch/aktuellesinformationen\", \"selector\": \"#informationList\", \"type\": \"static\", \"hash\": \"5cb7bfe4b6416f288bb19b5922b7a3a13b64dfb2543282f1be53eae179301775\"}, {\"label\": \"Anl\u00e4sse/Veranstaltungen Thalwil\", \"url\": \"https://www.thalwil.ch/anlaesseaktuelles\", \"selector\": \"#anlassList\", \"type\": \"static\", \"hash\": \"6da90578daefd67f9176599d579d42435fa280d3d54b403f4365f58c8562522a\"}, {\"label\": \"SP Thalwil\", \"url\": \"https://thalwil.spkantonzh.ch/\", \"selector\": \"#main\", \"type\": \"static\", \"hash\": \"349ecbc55006cdb1fa43e20bb67106c3c64600ded8794ef08b758c4707d8d64e\"}, {\"label\": \"FDP Thalwil\", \"url\": \"https://www.fdpthalwil.ch/aktuell/news\", \"selector\": \"#main-content\", \"type\": \"static\", \"hash\": \"bce3c327117329b7b5ee3dd307cf678fa640afc51e247093c69e13bda698d31a\"}, {\"label\": \"EVP Thalwil\", \"url\": \"https://evp-thalwil.ch/home\", \"selector\": \"#main\", \"type\": \"static\", \"hash\": \"521c4cce7002c51b78bfe74d1c2a540198fe9867a95780ab72611a9167e4adb1\"}, {\"label\": \"SVP Thalwil\", \"url\": \"https://www.svp-thalwil.ch/\", \"selector\": \"#page-zones__main\", \"type\": \"static\", \"hash\": \"2e368c9136024a6c8e9678ad191249c24aefb589e5565493b3bab6efff4c9bb0\"}, {\"label\": \"Mitte Thalwil\", \"url\": \"https://thalwil.die-mitte.ch/\", \"selector\": \"main\", \"type\": \"static\", \"hash\": \"0ac177d599cf0685de717f7bc59950c419c6861885af58ee041d26dc0b8dea5c\"}, {\"label\": \"Gr\u00fcne Thalwil\", \"url\": \"https://gruene-zh.ch/gr%C3%BCne-thalwil\", \"selector\": \"#content\", \"type\": \"static\", \"hash\": \"42c7fab0d784a6b370d048608d9116d494ae86558daf558789467394bc116bbc\"}, {\"label\": \"GLP Thalwil\", \"url\": \"https://thalwil.grunliberale.ch/aktuell.html\", \"selector\": \"#contentPage\", \"type\": \"static\", \"hash\": \"1a05667868f3ff744a98657708a96ea9fb2045389229320183316e7562964771\"}, {\"label\": \"Dorfverein Gattikon\", \"url\": \"https://www.dorfverein-gattikon.ch/\", \"selector\": \"#allrecords\", \"type\": \"static\", \"hash\": \"687e46d9f94f51e115870cbe111bdf0169bc4c8232ed897f5352e980544c29e2\"}, {\"label\": \"\u00d6kopolis\", \"url\": \"https://www.oekopolis.ch/\", \"selector\": \"#site-content\", \"type\": \"static\", \"hash\": \"c988013df3f5148277fb05b74a135bcc66795d626a112e6c7f7df0f19dad8507\"}, {\"label\": \"Digitales Amtsblatt Thalwil\", \"url\": \"https://epublikation.ch/#!/search/publications?metaTags=invitations&metaTags=enactments&metaTags=votes&metaTags=citizenship&metaTags=planning&metaTags=building&metaTags=traffic&metaTags=protection&metaTags=deaths&metaTags=court&metaTags=announcements&metaTags=public_bodies&municipalityName=Thalwil\", \"selector\": \"div.app-content-center\", \"type\": \"dynamic\", \"hash\": \"23f5934a8affc071e9f5a4fb9355a8f94a6d4b1f5e147f405240f9bc2e599249\"}, {\"label\": \"Thalwil politisch Facebook\", \"url\": \"https://de-de.facebook.com/groups/thalwilpolitsch/\", \"selector\": \"[data-pagelet=\\"GroupFeed\\"]\", \"type\": \"dynamic\", \"hash\": \"d705a2a4b8538cee156b0f3a371259a8e2f009d1a580abd04b5c3028e9b07b0c\"}]}"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  notify:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.build-matrix.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get install sqlite3
          sudo apt-get install chromium-browser

      - name: Check website
        id: website
        run: echo '::set-output name=hash::$(./website_hash.py -u ${{ matrix.url }} -s ${{ matrix.selector }})'
      
      # - name: Check if there are changes in the repo
      #   run: |
      #     git status --porcelain
      #     if [[ -z $(git status --porcelain) ]];
      #     then
      #       echo "Repo is clean"
      #       echo '::set-output name=changed::0'
      #     else
      #       echo "Repo is dirty"
      #       echo '::set-output name=changed::1'
      #     fi
      #   id: changes
      #   
      # - name: Commit and push to repo
      #   if: steps.changes.outputs.changed == 1 # only try to commit if there are actually changes
      #   uses: github-actions-x/commit@v2.9
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     push-branch: main
      #     name: GitHub Action Bot
      #     email: oderbolz@gmail.com
      #     commit-message: Update website.csv with updated hashes
      #     rebase: 'true'

      - name: Notify telegram about website changes
        if: ${{ steps.website.outputs.hash }} != ${{ matrix.hash }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            🟢 Website changed: [${{matrix.label }}](${{ matrix.url }})"

      - name: Notify telegram failure
        if: ${{ failure()  || cancelled() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            🔴 [Website Checker Job Failed](https://github.com/metaodi/website-monitor/actions/runs/${{ github.run_id }}?check_suite_focus=true)
