name: Check Thalwil websites

on:
  schedule:
    - cron:  '16 5-21 * * *' # every 30min
    - cron:  '10 3 * * 0' # weekly on Sunday at 3:10am (check all entries)
  workflow_dispatch:

jobs:
  notify_thalwil_websites:
    uses: metaodi/website-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/thalwil.csv
      check-all: ${{ github.event.schedule == '10 3 * * 0' }}
    secrets:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_TO }}
      TELEGRAM_ERROR_CHAT_ID: ${{ secrets.TELEGRAM_ERROR_CHAT_ID }}
      WIREGUARD_CONFIG: ${{ secrets.WIREGUARD_CONFIG }}

